#!/usr/bin/env python3
"""Flask server for the devtest app.

The same four routes as the FastAPI server, registered by the same call:
`srv.register_flask` puts login, context refresh, the dispatcher and info on
whatever it is given — here the application itself, because this file *is* the
application. Plugin loading, model generation and the seed data come from
devtest.py, so both servers and the test harness run the same application.

Run from this directory:  python server_flask.py
"""
import os

from flask import Flask

import devtest  # also puts the kitebase package on sys.path  # noqa: E402
import kitebase.server_utils as srv  # noqa: E402

# ── Application ─────────────────────────────────────────────────────────────

# Listening is the application's choice: the library only speaks.
srv.setup_logging(os.environ.get('KITEBASE_LOG_LEVEL', 'INFO'),
                  os.environ.get('KITEBASE_LOG_FILE'))

kitebase_app, plugins = devtest.setup()

import model  # type: ignore  # generated by devtest.setup()  # noqa: E402

kitebase_app.initialize_db(plugins.config["db_engine"], model)
plugins.load_all_locales()
devtest.seed(kitebase_app, model)

# 32 bytes at least: below that PyJWT warns that the key is weak for
# HS256, and a warning nobody can act on is a warning people learn to skip.
SECRET_KEY = os.environ.get("SECRET_KEY", "development-secret-key-not-for-service")

app = Flask(__name__)
app.config["SECRET_KEY"] = SECRET_KEY

# ── Routes ──────────────────────────────────────────────────────────────────

srv.register_flask(app, kitebase_app, plugins, SECRET_KEY)


# A built client, when there is one: `clientui/`, mounted where `client:` in
# config.yaml says - at the root, devtest being the application itself.
srv.serve_client_flask(app, os.path.dirname(os.path.abspath(__file__)), plugins.config)


if __name__ == "__main__":
    port = plugins.config.get("api", {}).get("port", 8300)
    print(f"\n🚀 Kitebase devtest (Flask) on port {port}\n")
    app.run(host="0.0.0.0", port=port)
